### ISSUE TITLE
check unit conversions in cleaning workflows 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#103]
Add unit checks for temperature and precip to ERA-5 and CMIP6 clean-up workflows - standardize to K and mm/day respectively

**Comment by brews** [comment]
What do you think this would involve? Checking for a realistic data range? Using `pint`?

**Comment by dgergel** [comment]
I was thinking we would check the units attribute (I think this should exist in CMIP6), and with ERA-5 we know the units and can change them in the workflow. I haven't used `pint` before but heard of it, it might be useful here!

**Comment by brews** [comment]
It would be good to check the final data we're about to output to `clean` storage for the attributes/metadata we want, even beyond unit annotations.

(same goes for final data output from the main workflow)

**Comment by dgergel** [comment]
I totally agree. This issue was just intended to be a reminder to check units and standardize in our cleaning workflows, especially for precip, as ERA-5 is in m for example, and the wet day frequency correction assumes that precip is in mm/day

**Comment by brews** [comment]
Ahhh, gotcha.  I see where you're coming from. That sounds like a priority. 👍

**Comment by dgergel** [comment]
@brews did we ever take care of this for CMIP6 precip or do we still need to do it? Doing some housekeeping today...

**Comment by brews** [comment]
@dgergel We have this bit here https://github.com/ClimateImpactLab/dodola/blob/3357802406a1e2aa3da37ffed8e2e3d49cee854b/dodola/core.py#L415

This was in `dodola` v0.4.0 used by `dodola cleancmip6` on the CLI.

It looks like `dodola cleancmip6` is used for in `workflows/templates/clean-cmip6.yaml` https://github.com/ClimateImpactLab/downscaleCMIP6/blob/540445394437c9f2ca40e40ba93e14172e85d0a7/workflows/templates/clean-cmip6.yaml#L119.

I don't see us using that in `workflows/templates/clean-era5.yaml`. The closest we have is this script in a "standardize" step: https://github.com/ClimateImpactLab/downscaleCMIP6/blob/540445394437c9f2ca40e40ba93e14172e85d0a7/workflows/templates/clean-era5.yaml#L113

So, CMIP6: yes. ERA-5: Not in these workflows.
