### ISSUE TITLE
post-processing step for bias correction needed 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#117]
With the additional diagnostics option in `sdba` that we are now leveraging for downscaling so that we have the quantiles computed during bias correction, we need one additional step so that `xclim` can ingest the quantiles correctly. We need to update the quantiles to be a coordinate of `scen` and need to do this either in `dodola` after adjusting or in the dc6 workflow.  Right now the quantiles are a data variable and not a coordinate of `scen`, so `xclim` can't correctly ingest them. I _think_ that putting this into `dodola` makes more sense, in the qdm adjust function. It would look something like this: 

```ds_biascorrected = ds_biascorrected['scen'].assign_coords(sim_q=ds_biascorrected.sim_q)```

cc @brews @kemccusker

**Comment by brews** [comment]
@dgergel, in dodola, you're saying you'd need change to the 'out' variable like after line 99 here:
https://github.com/ClimateImpactLab/dodola/blob/18b42c1b71b02f479c9cc5f5c682e99bc49cf8d6/dodola/core.py#L99 ?

**Comment by dgergel** [comment]
@brews I think we can close this as we've taken care of this with the QDM workflow updates. Sound right to you?

**Comment by brews** [comment]
@dgergel Yeah, I think this is good for now.

Closing.
