### ISSUE TITLE
decide on attributes and metadata for downscaled data 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#179]
We need to iterate and decide on how we want to set up our attributes and metadata for downscaled zarr stores - this is just a placeholder to start the discussion.

**Comment by brews** [comment]
I think there is a more essential low-hanging fruit version of this. As it is right now, we're just dumping blob data into azure storage. We need at least enough basic metadata to know what we're looking at, at the simplest level (source_id, variable_id, etc...), even if that information is not encoded in the data path.

**Comment by dgergel** [comment]
That makes sense. So first pass can be all of the basic identifiers - e.g. SSP, model, variable, frequency, etc - along with methods used and documented. We can iron out the CF-conventions-compliance part of this afterward. Sound good? 

In terms of what data actually needs metadata, I'm thinking the bias corrected and downscaled outputs - any intermediate outputs as well? Cleaned and rechunked CMIP6 input data to bias correction perhaps? 

Thinking we add a function in `dodola` for now that adds attributes based on the step of the workflow and on the tuple identifiers unique to each GCM/variable/scenario. We would have those as parameters in the workflow already. How does that sound to you @brews?

**Comment by brews** [comment]
@dgergel 

> Thinking we add a function in `dodola` for now that adds attributes based on the step of the workflow and on the tuple identifiers unique to each GCM/variable/scenario. We would have those as parameters in the workflow already. How does that sound to you @brews?

The immediate issue is that metadata needs to be preserved between workflow steps because it's useful to validate and write final-ish output. All of this "immediately essential" data (stuff we use for I/O) is present as soon as we download it from CMIP6-in-the-cloud. We just need to hold on to it. Right now, https://github.com/ClimateImpactLab/dodola/issues/116 is likely the most obvious offender.
