### ISSUE TITLE
add precip wet day frequency correction post-downscaling 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#182]
We have already added the wet day frequency correction in to the workflow pre-bias correction, but we need to add it in post-downscaling as well. This already exists in dodola as the `post` flag option, just need to add it to our pipeline.

**Comment by brews** [comment]
We have the workflow template but it reads the entire Zarr store into memory and bombs with the 0.25 degree "post" application after QPLAD. Consider incorporating it into `dodola apply-qplad`?

**Comment by dgergel** [comment]
closed with #521 and #522 (and others)
