### ISSUE TITLE
clean CMIP6 fails on EC-Earth3-Veg due to running out of memory 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#209]
No traceback in logs, but OOM error

**Comment by brews** [comment]
Is this spec even merged?

**Comment by brews** [comment]
I just pushed through PR #239. This bumps the memory cap on the "standardize" step and might fix this, @dgergel.

**Comment by dgergel** [comment]
Awesome. I'll try running it again in a bit.

**Comment by dgergel** [comment]
closed with #239
