### ISSUE TITLE
Add root metadata to clean-cmip6 output

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#327]
The final outputs from `workflows/templates/clean-cmip6.yaml` do not have all the root metadata from `workflows/templates/create-output-metadata-json.yaml`. We should check that we have the metadata we need and add JSON metadata to the final output from the clean-cmip6 WorkflowTemplate.

We should at least have `dc6_workflow_name` and `dc6_workflow_uid` so we can trace data heritage and debug if the cleaning step is run in isolation.

**Comment by dgergel** [comment]
i think we can safely close this @brews, correct?

**Comment by brews** [comment]
Hmm. This is still an outstanding issue. It's definitely not something that needs to be fixed before any data is run or submitted (obviously).

I think it's okay to close this if you want to remove stale issues, @dgergel.
