### ISSUE TITLE
Consolidate intermediate clean-cmip6 to output to boot disk

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#328]
As it's written, `workflows/templates/clean-cmip6.yaml` outputs its intermediate data to GCS bucket Zarr Stores. This can rack up costs. We might have a chance to save time and costs by consolidating cleaning steps to a single pod with intermediate data saved and passed through the pod's boot disk.

We had success doing this with [pre-processing the input to biascorrection](https://github.com/ClimateImpactLab/downscaleCMIP6/blob/96b29803b5446f01f2f25e0a620ed771a8dd10f2/workflows/templates/qdm.yaml#L125).

Using persistent disk claims to pass intermediate data between multiple pods is another option but this will be more complex to implement so I suggest using boot disk as a first step.

The clean-cmip6 ls a bit of a mess so it could use a cleanup either way.

**Comment by brews** [comment]
Also see #327.

**Comment by dgergel** [comment]
same for this one

**Comment by brews** [comment]
Yeah, this one is stale. We gave this up because putting intermediate data in memory or on a temporary disk means that we can't check the intermediate output of runs. Checking intermediate output was pretty important for debugging and development.

Closing.
