### ISSUE TITLE
ACCESS-ESM1-5 pr cleaning fails, can't concatenate historical to ssps 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#443]
Didn't manage to grab a log error for this one: 

Workflow is here: https://argo.cildc6.org/archived-workflows/default/5b708336-ca41-490d-987c-b69b6c554fc8?nodeId=clean-access-esm1-5-pr-lbv5w-1794398330

```
Unable to resolve: "steps.concatenate-hist-to-ssp.outputs.parameters.out-zarr"
```

**Comment by dgergel** [comment]
@brews are you able to find a log error for this one?? I wasn't so it's a bit tricky to debug

**Comment by dgergel** [comment]
@emileten could you retry this to see if it was a one-off error?

**Comment by emileten** [comment]
@dgergel I retried a `clean-cmip6` workflow for `ACCESS-ESM1-5` `pr` and it succeeded. Here : https://argo.cildc6.org/archived-workflows/default/c716e9a9-04a1-488f-ac8e-ce724ea68b2a. 

Closing this !
