### ISSUE TITLE
GFDL-ESM4-pr.yaml historical fails biascorrected-preprocess regridding before downscaling

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#494]
Workflow run: https://argo.cildc6.org/workflows/default/e2e-gfdl-esm4-pr-krwqv

The historical biascorrected output fails during its preprocessing regridding down to 0.25 degree. This regridding is done year-by-year in independent tasks and written to the region of a single zarr store.

A sample of the logged error from regridding is
```

/opt/conda/lib/python3.9/site-packages/xesmf/backend.py:53: UserWarning: Latitude is outside of [-90, 90]
  warnings.warn('Latitude is outside of [-90, 90]')
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:496: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
Traceback (most recent call last):
  File "/argo/staging/script", line 68, in <module>
    ds_out.to_zarr(out_zarr, region={"time": target_idx_slice}, mode="a")
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2031, in to_zarr
    return to_zarr(
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1361, in to_zarr
    _validate_region(dataset, region)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1274, in _validate_region
    raise ValueError(
ValueError: when setting `region` explicitly in to_zarr(), all variables in the dataset to write must have at least one dimension in common with the region's dimensions ['time'], but that is not the case for some variables here. To drop these variables from this dataset before exporting to zarr, write: .drop(['bnds'])
```

The log from the step priming the output zarr store shows:

```
first_year=1950, last_year=2014
ds_out=<xarray.Dataset>
Dimensions:  (time: 23725, lat: 720, lon: 1440, bnds: 2)
Coordinates:
  * bnds     (bnds) float64 1.0 2.0
  * time     (time) object 1950-01-01 12:00:00 ... 2014-12-31 12:00:00
  * lon      (lon) float64 -179.9 -179.6 -179.4 -179.1 ... 179.4 179.6 179.9
  * lat      (lat) float64 -89.88 -89.62 -89.38 -89.12 ... 89.38 89.62 89.88
Data variables:
    pr       (time, lat, lon) float32 dask.array<chunksize=(365, 2, 1440), meta=np.ndarray>
    sim_q    (time, lat, lon) float32 dask.array<chunksize=(365, 2, 1440), meta=np.ndarray>
Attributes: (12/47)
    Conventions:                  CF-1.7 CMIP-6.0 UGRID-1.0
    activity_id:                  CMIP
    contact:                      climatesci@rhg.com
    creation_date:                2019-07-27T03:52:40Z
    data_specs_version:           01.00.27
    dc6_bias_correction_method:   Quantile Delta Method (QDM)
    ...                           ...
    table_id:                     day
    tracking_id:                  hdl:21.14100/fc9d6bda-4932-469c-9d06-bf1779...
    variable_id:                  pr
    variant_label:                r1i1p1f1
    version_id:                   v20190726
    regrid_method:                nearest_s2d
ds_out[non_time]=<xarray.Dataset>
Dimensions:  (lat: 720, lon: 1440)
Coordinates:
  * lat      (lat) float64 -89.88 -89.62 -89.38 -89.12 ... 89.38 89.62 89.88
  * lon      (lon) float64 -179.9 -179.6 -179.4 -179.1 ... 179.4 179.6 179.9
Data variables:
    *empty*
Attributes: (12/47)
    Conventions:                  CF-1.7 CMIP-6.0 UGRID-1.0
    activity_id:                  CMIP
    contact:                      climatesci@rhg.com
    creation_date:                2019-07-27T03:52:40Z
    data_specs_version:           01.00.27
    dc6_bias_correction_method:   Quantile Delta Method (QDM)
    ...                           ...
    table_id:                     day
    tracking_id:                  hdl:21.14100/fc9d6bda-4932-469c-9d06-bf1779...
    variable_id:                  pr
    variant_label:                r1i1p1f1
    version_id:                   v20190726
    regrid_method:                nearest_s2d
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:496: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct p
arameter in a future version.
  ds_out = xr.apply_ufunc(
```

Blocking progress on run #244.

**Comment by delgadom** [comment]
example datasets:
```
gs://clean-b1dbca25/cmip6/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/pr/gr1/v20190726.zarr
```
```
gs://clean-b1dbca25/cmip6/ScenarioMIP/NOAA-GFDL/GFDL-ESM4/ssp585/r1i1p1f1/day/pr/gr1/v20180701.zarr
```

**Comment by dgergel** [comment]
@brews is this still a bug that needs fixing?

**Comment by brews** [comment]
@dgergel Hmmm... I'm not too sure off the top of my head. I don't see any precip runs in the archive for GFDL-ESM4. We'd need to rerun it to see. This might have also been a bad dim/coord on input historical data — but we've changed the precip workflow enough so that I think it's worth confirming this is still an issue.

**Comment by emileten** [comment]
@brews @dgergel this model is still failing for the same reason. Here is the workflow we ran today : https://argo.cildc6.org/archived-workflows/default/97544aa8-da09-4d68-a0e7-337d5e9f0be1.

**Comment by emileten** [comment]
The error message says explicitly : 

```
ValueError: when setting `region` explicitly in to_zarr(), all variables in the dataset to write must have at least one dimension in common with the region's dimensions ['time'], but that is not the case for some variables here. To drop these variables from this dataset before exporting to zarr, write: .drop(['bnds'])
```

Indeed, if I look at an example dataset that failed regridding, there is a `bnds` coordinates variable, that doesn't have any dimensions. That variable is not present at the same step in `BCC-CSM2-MR`, which did not fail. 

This variable is sticking around from the raw data on through that step. E.g. it's in `gs://raw-305d04da/cmip6/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/pr/gr1/v20190726.zarr`. 

I think it's safe to drop this coordinate variable from the cleaning steps on. I don't think it's going to provide any useful information.

**Comment by brews** [comment]
@emileten I have an alternative solution here: https://github.com/ClimateImpactLab/downscaleCMIP6/pull/531

I updated the distributed-regrid workflowTemplate so that it dynamically detects which dimensions are and are not related to the "time" dim. This is so it knows whether to write the variable when the output zarr store is first primed or later when the zarr store is written-to in "regions" (annual chunks in the case of regridding).

The error here is because "bnds" is being written in one of the region-writing steps — but it doesn't depend on "time" — so it can't actually be part of a regionally write. So, rather than removing the info from the raw data, this PR identifies that "bnds" needs to be written to the output zarr store when the zarr store is first primed.

**Comment by brews** [comment]
I hate to say it after you whipped together [that dodola PR](https://github.com/ClimateImpactLab/dodola/pull/177), @emileten, but my hunch is to prefer PR #531 because this fix means we don't need to modify the input CMIP6 data as much.

If PR #531 ends up **not** solving the problem, then I'd say go with https://github.com/ClimateImpactLab/dodola/pull/177 and remove the troublesome bits.

But, I'm curious if anyone has arguments otherwise, or if you have a feeling on this @emileten (or others)?

**Comment by emileten** [comment]
No all good @brews. It was a very small PR. 

Also, I agree your solution is better as it's always better to keep the data we have, even if it's not useful at the moment.
