### ISSUE TITLE
 NorESM2-LM e2e DTR run fails downscaled validation on polar values out of range

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#500]
Workflow : https://argo.cildc6.org/archived-workflows/default/f6dc456f-daa0-4d11-81db-e84e0c1d6d41?nodeId=e2e-noresm2-lm-dtr-ql8ds-264390888

Log :  

```
assert (
AssertionError: diurnal temperature range max is <xarray.DataArray 'dtr' ()>
dask.array<nanmax-aggregate, shape=(), dtype=float32, chunksize=(), chunktype=numpy.ndarray> for polar northern latitudes
```

**Comment by emileten** [comment]
The max over southern and non polar values is `118.89946`.

**Comment by dgergel** [comment]
@emileten I think we can close this now?

**Comment by dgergel** [comment]
closed due to switch to additive approach for tasmin

**Comment by emileten** [comment]
> @emileten I think we can close this now?

yes thanks @dgergel!
