### ISSUE TITLE
NorESM2-LM precipitation e2e workflow fails at pre-QDM simulation regrid

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#529]
workflow : https://argo.cildc6.org/archived-workflows/default/20980934-7498-46da-b1f0-4e5b380816b1

This already failed a month ago for the same reason in this workflow : https://argo.cildc6.org/archived-workflows/default/3a023129-39cf-4742-b41f-42a3628c44b3. 

log : 
```
INFO:dodola.services:Starting dodola service regrid with args=('gs://scratch-170cd6ec/20980934-7498-46da-b1f0-4e5b380816b1/e2e-noresm2-lm-pr-9cdwl-3521027987/rechunked.zarr',), kwargs={'out': 'gs://scratch-170cd6ec/20980934-7498-46da-b1f0-4e5b380816b1/e2e-noresm2-lm-pr-9cdwl-4267003178/out.zarr', 'method': 'conservative', 'domain_file': 'gs://support-c23ff1a3/domain.1x1.zarr', 'weights_path': None, 'astype': 'float32', 'add_cyclic': None})
INFO:dodola.repository:Read gs://scratch-170cd6ec/20980934-7498-46da-b1f0-4e5b380816b1/e2e-noresm2-lm-pr-9cdwl-3521027987/rechunked.zarr
INFO:dodola.repository:Read gs://support-c23ff1a3/domain.1x1.zarr
Traceback (most recent call last):
  File "/opt/conda/bin/dodola", line 33, in <module>
    sys.exit(load_entry_point('dodola', 'console_scripts', 'dodola')())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/dodola/dodola/cli.py", line 578, in regrid
    services.regrid(
  File "/opt/dodola/dodola/services.py", line 31, in service_logger
    func(*args, **kwargs)
  File "/opt/dodola/dodola/services.py", line 614, in regrid
    regridded_ds = xesmf_regrid(
  File "/opt/dodola/dodola/core.py", line 459, in xesmf_regrid
    regridder = xe.Regridder(
  File "/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py", line 698, in __init__
    grid_in, shape_in, input_dims = ds_to_ESMFgrid(
  File "/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py", line 129, in ds_to_ESMFgrid
    lon_b, lat_b = _get_lon_lat_bounds(ds)
  File "/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py", line 75, in _get_lon_lat_bounds
    lon_b = cfxr.bounds_to_vertices(lon_bnds, ds.cf.get_bounds_dim_name('longitude'), order=None)
  File "/opt/conda/lib/python3.9/site-packages/cf_xarray/accessor.py", line 1928, in get_bounds_dim_name
    assert len(bounds_dims) == 1
AssertionError
```

Blocking progress on #420

**Comment by emileten** [comment]
`cf` complains because the longitude bounds are not 2D.

Reading `gs://scratch-170cd6ec/20980934-7498-46da-b1f0-4e5b380816b1/e2e-noresm2-lm-pr-9cdwl-3521027987/rechunked.zarr`, the `lon_bnds` are 3D. There is a time dimension : 

<img width="732" alt="Screen Shot 2022-02-08 at 11 19 46 AM" src="https://user-images.githubusercontent.com/45140658/152905466-2395a2e0-ad06-42a7-bbfd-4601e2fbaa8b.png">

Oddly enough, the `lon_bnds` are _not_ constant across that dimension... Between 2004 and 2014 included, the values are fine, and then in the rest of the period, the edges of the bounds array are kind of wrong, I think. The left edge is `[-1.25, 1.25]`, and the right edge is `[356.25, 358.75]`. 

That's pretty odd. Thoughts @dgergel ? I think we need to add a step to correct that in the cleaning part of the workflow for the models to run through the end.

**Comment by dgergel** [comment]
@emileten the fact that the values are fine bw 2004 and 2014, and then incorrect for 2015 - 2100, makes me think that something went wrong in the concatenation of `lon_bnds` between historical and the ssp runs and that's why this is so strange. I would check for consistency in dim names for bounds between hist and future for this model, definitely seems like we are missing something in the cmip6-clean workflow.

**Comment by emileten** [comment]
@dgergel in fact, it's a characteristic of the raw data rather than a bug in our pipeline. 

There are two longitude band at the prime meridian that are different between the future data and historical data grid in the `NorESM2-LM` raw data we're using. 

In the historical data, the longitudinal bounds are as follows :  

`[  0.  ,   1.25]`
... 2.5 degrees  ... 
`[356.25, 360.  ]`. 

In the future data, in contrast : 

`[  -1.25  ,   1.25]`
... 2.5 degrees  ... 
`[356.25, 358.75.  ]`. 

When we concatenate these two datasets, we (correctly...) insert a time dimension in the longitudinal bounds. 

We could change the bound definition of the future data to match the historical data. But that's altering the data. Is this a bug from `NorESM2-LM`?
