### ISSUE TITLE
Authentication Error: When trying to write the data more than 5 yrs into netcdf file

### ISSUE THREAD

**Issue by devosse1** [ClimateImpactLab/downscaleCMIP6#626]
* Downscale version: Conventions:  CF-1.7 CMIP-6.2
    activity_id:   ScenarioMIP
    contact:  climatesci@rhg.com
    data_specs_version: 01.00.30
* Python version: Python 3.9
* Operating System: Ubuntu

### Description

ClientAuthenticationError: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed

Ran into a deserialization error. Ignoring since this is failsafe deserialization
Traceback (most recent call last):
  File "/home/user/my_project_dir/anaconda3/lib/python3.9/site-packages/msrest/serialization.py", line 1509, in failsafe_deserialize

### What I Did

I am calculating month Tamax mean and then writing it into netcdff file as I need the downscale data to be fed as input in a model
subset = all_datasets.sel(
    lon=slice(25, 45),
    lat=slice(-10, 10),
)
mtasmax = subset.resample(time="M").mean()
delayed_obj = mtasmax.sel( time=slice("2025-01-01", "2030-12-31")).to_netcdf('rgrp_yr2_2025_2030.nc',
                                compute=False)

if I run for 10 years or 5 years or if the notebook is running for quie some time it shows this Client authentication error

can some please in regards to this?
If there was a crash, please include the traceback here.
```
![image](https://user-images.githubusercontent.com/60099425/192335221-73a2190b-6e68-44c4-9e89-9c1cf0a1d1d4.png)

**Comment by delgadom** [comment]
Thanks for the question and interest in the dataset! Sorry to hear you're having this issue.

This seems to me to be a Microsoft Planetary Computer authentication issue - @TomAugspurger - if you're around - any advice on how to handle this issue?

@devosse1 you might be able to get help by filing an issue or asking for advice from the 
https://github.com/microsoft/PlanetaryComputer team & users, by filing an [issue](https://github.com/microsoft/PlanetaryComputer/issues) or visiting their [discussions](https://github.com/microsoft/PlanetaryComputer/discussions) page

**Comment by TomAugspurger** [comment]
Discussing this at https://github.com/microsoft/PlanetaryComputer/issues/109. I think this can be closed.

**Comment by devosse1** [comment]
sure
