### ISSUE TITLE
SSP1-2.6 precipitation data 

### ISSUE THREAD

**Issue by devosse1** [ClimateImpactLab/downscaleCMIP6#627]
Downscale version: Conventions: CF-1.7 CMIP-6.2
activity_id: ScenarioMIP
    contact: [climatesci@rhg.com](mailto:climatesci@rhg.com)
    data_specs_version: 01.00.30
Python version: Python 3.9
Operating System: Ubuntu
### Description

Actually I am using these downscaled CMIP model data to input it in an ecological model and then compare its result in various performances. I need Precp, Tmax, Tmin
But since SSP1-2.6 precipitation data is not present , it is causing be issues.
I know in the website, it was written "At the time of running, no ssp1-2.6 precipitation data was available" but I was wondering if it can be run and provided now as it is really important for our projections, a possible timeline will also help.
And if it is not possible any alternate that you can suggest?
I'll really appreciate your help in regards to it.

```

**Comment by delgadom** [comment]
Hi, and thanks for your interest in the data! The footnote you're referencing only applies to the FGOALS-g3 model. SSP 1-2.6 precip simulations are available for all other models which have ssp1-2.6 indicated in the table of [available institutions, models, and scenarios by license collection](https://github.com/ClimateImpactLab/downscaleCMIP6#available-institutions-models-and-scenarios-by-license-collection)

**Comment by delgadom** [comment]
I just updated [the footnote](https://github.com/ClimateImpactLab/downscaleCMIP6/blob/master/README.rst#id9) to more clearly indicate that it only applies to this model:
> At the time of running, no ssp1-2.6 precipitation data was available for the FGOALS-g3 model. Therefore, we provide tasmin and tamax for this model and experiment, but not pr. All other model/experiment combinations in the above table include all three variables.

Does this address the issue for you?

**Comment by delgadom** [comment]
closing this - @devosse1 feel free to reopen or create another issue if you have any other questions!
