### ISSUE TITLE
CanESM moved to CC-BY collection on planetarycomputer

### ISSUE THREAD

**Issue by delgadom** [ClimateImpactLab/downscaleCMIP6#660]
As of May 4, the CCMA/CanESM5 model results have been moved to the PC/CC-BY collection (from CC-BY-SA) following the decision by the CMIP6 consortium to loosen all licenses.

new collection location: https://planetarycomputer.microsoft.com/dataset/cil-gdpcir-cc-by

This change should be reflected in the readme and also on the planetary computer readme.

**Comment by brews** [comment]
I can throw these changes together. Reassigning this issue to myself.

**Comment by delgadom** [comment]
re-opening - we still need to update [microsoft/planetarycomputerexamples](https://github.com/microsoft/PlanetaryComputerExamples/tree/main/datasets/cil-gdpcir)

**Comment by brews** [comment]
@delgadom Is that just a matter of doing a PR to that repo?

**Comment by delgadom** [comment]
ok I proposed the relevant edits. I didn't realize but Tom has already done the major changes needed for both readmes and example notebooks. The only things I caught were text changes needed ("the GDPCIR dataset is made up of ~three~two collections"). I think we can close this now - if MSFT doesn't want to incorporate these changes that's fine but we've done our part :)
