### ISSUE TITLE
add ERA-5 precip aggregation scripts

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#81]
currently the ERA-5 workflow directory only contains scripts for aggregating temperature - precip ones need to be added as well

**Comment by merfish** [comment]
Added to the branch era5_climo titled, `daily_precip_era5_v1_1.ipynb`. will update for grib files and to match temp download/aggregation.

**Comment by dgergel** [comment]
closed via #83
