### ISSUE TITLE
add ERA-5 precip validation script(s) 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#82]
So far our validation scripts only include temperature - need to update to include precip

**Comment by merfish** [comment]
Added to the era5_climo branch, titled `validate_era5_daily_precip.ipynb`. will update with grib file versions (apologies for the histogram output).

**Comment by dgergel** [comment]
Wonderful, thanks @merfish! Once we have the grib file version updates let's get them all merged into `main`.

**Comment by dgergel** [comment]
closed via #83
