### ISSUE TITLE
updates needed in dc6-workflow

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#99]
As a follow-up to #93, we need to clean up the following aspects of the main bias correction and downscaling workflow: 

- [ ] update `biascorrect-firstfutureyear` to 1950
- [ ] currently the workflow only adjusts one run, a historical and future projection concatenated together. Need to update to have a "train QDM" step and then branch out into "apply historical" (1950-2014) and "apply future" (2015 - 2100) for each SSP, and those need to have the correct time slices available (e.g. future SSPs need to have historical data, historical model run needs SSP245 if that's the decision we make in terms of including/excluding future years)
- [ ] update `biascorrect-lastfutureyear` to 2100 

cc @brews (feel free to add anything I've missed)

**Comment by brews** [comment]
So, from what's described, it sounds like we'd set `biascorrect-firstfutureyear` to 2015 and `biascorrect-lastfutureyear` to 2100 (this range is inclusive).

We'd then want to have these separate "apply historical" and "apply future" stages and add something like `biascorrect-firsthistoricalyear` and `biascorrect-lasthistoricalyear` parameters (set to 1950 and 2014, respectively).
